name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: |
          cd REACTJS/frontend
          npm ci
          
      - name: Build project
        run: |
          cd REACTJS/frontend
          npm run build
          
      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r REACTJS/frontend/dist deployment/
          cp REACTJS/deployment_files/Docker-compose.yml deployment/
          cp REACTJS/deployment_files/Dockerfile.frontend deployment/
          cp REACTJS/deployment_files/Dockerfile.backend deployment/
          cp REACTJS/deployment_files/nginx.conf deployment/
          tar -czf deployment.tar.gz -C deployment .
        
      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "deployment.tar.gz"
          target: "/tmp"
          
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p ~/app
            tar -xzf /tmp/deployment.tar.gz -C ~/app
            cd ~/app
            docker-compose down || true
            docker-compose up -d --build