name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: |
          ls -la
          cd $GITHUB_WORKSPACE/savenserve/REACTJS/frontend || (echo "Directory not found, trying alternative path" && cd $GITHUB_WORKSPACE/savenserve/REACTJS/frontend)
          npm ci
          
      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE/savenserve/REACTJS/frontend || (echo "Directory not found, trying alternative path" && cd $GITHUB_WORKSPACE/savenserve/REACTJS/frontend)
          npm run build
          
      - name: Create deployment package
        run: |
          mkdir -p deployment
          # List directories to debug
          echo "Listing current directory:"
          ls -la
          
          # Use correct paths with fallbacks
          FRONTEND_PATH="$GITHUB_WORKSPACE/savenserve/REACTJS/frontend"
          if [ ! -d "$FRONTEND_PATH" ]; then
            echo "Trying alternative frontend path"
            FRONTEND_PATH="$GITHUB_WORKSPACE/savenserve/REACTJS/frontend"
          fi
          
          DEPLOYMENT_PATH="$GITHUB_WORKSPACE/deployment_files"
          if [ ! -d "$DEPLOYMENT_PATH" ]; then
            echo "Trying alternative deployment files path"
            DEPLOYMENT_PATH="$GITHUB_WORKSPACE/savenserve/deployment_files"
          fi
          
          # Copy files with proper paths
          cp -r $FRONTEND_PATH/dist deployment/ || echo "Warning: Could not copy frontend dist"
          cp $DEPLOYMENT_PATH/Docker-compose.yml deployment/ || echo "Warning: Could not copy Docker-compose.yml"
          cp $DEPLOYMENT_PATH/Dockerfile.frontend deployment/ || echo "Warning: Could not copy Dockerfile.frontend"
          cp $DEPLOYMENT_PATH/Dockerfile.backend deployment/ || echo "Warning: Could not copy Dockerfile.backend"
          cp $DEPLOYMENT_PATH/nginx.conf deployment/ || echo "Warning: Could not copy nginx.conf"
          
          # Create archive
          tar -czf deployment.tar.gz -C deployment .
        
      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "deployment.tar.gz"
          target: "/tmp"
          
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p ~/app
            tar -xzf /tmp/deployment.tar.gz -C ~/app
            cd ~/app
            docker-compose down || true
            docker-compose up -d --build